contact_links:
  - name: âš ï¸ Application issue
    url: https://github.com/komikku-app/komikku/issues/new/choose
    about: Issues and requests about the app itself should be opened in the Komikku repository instead
  - name: ğŸ–¥ï¸ Website
    url: https://komikku-app.github.io/docs/guides/getting-started
    about: Guides, troubleshooting, and answers to common questions
