contact_links:
  - name: âš ï¸ Application issue
    url: https://github.com/komikku-app/komikku/issues/new/choose
    about: Issues and requests about the app itself should be opened in the Komikku repository instead
  - name: ğŸ“¦ Extensions
    url: https://komikku-repo.github.io/extensions
    about: List of all available extensions with download links
  - name: ğŸ–¥ï¸ Website
    url: https://komikku-app.github.io/help/
    about: Guides, troubleshooting, and answers to common questions
